{% set version = "0.5.0" %}

package:
  name: pyct-packages
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyct/pyct-{{ version }}.tar.gz
  sha256: dd9f4ac5cbd8e37c352c04036062d3c5f67efec76d404761ef16b0cbf26aa6a0

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >=3.7

outputs:
  - name: pyct-core
    build:
      noarch: python
      entry_points:
        - pyct=pyct.__main__:main
      script: {{ PYTHON }} -m pip install . -vv

    requirements:
      run_constrained:
        - pyct {{ version }}
      host:
        - python >=3.7
        - param >=1.7.0
        - pip
      run:
        - python >=3.7
        - param >=1.7.0
        - setuptools >=61.0
        # cli
        - pyyaml
        - requests

    test:
      imports:
        - pyct
      commands:
        - pip check
        - pyct --help
      requires:
        - pip

  - name: pyct
    build:
      noarch: python

    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - {{ pin_subpackage('pyct-core', exact=True) }}

    test:
      imports:
        - pyct
        - pyct.cmd

about:
  home: https://github.com/holoviz-dev/pyct
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Common tasks for package building (e.g. bundle examples)
  doc_url: https://github.com/holoviz-dev/pyct#pyctbuild
  dev_url: https://github.com/holoviz-dev/pyct

extra:
  recipe-maintainers:
    - ceball
    - ocefpaf
