travis:
  secure:
    BINSTAR_TOKEN: O/RA1Er+43GFwjteD3UKzdZQSnyIexcXiA+e+r7lLpWXk//2MBAZQxO/XQTMaBGk1miDChJlx7tc85obdNQ3xJSTo7WRGc3eJJWtznaN6fi16zJeZRvrnAZTbAHqy/S1a/RyJITb8d9yfelVU8U+NO3u9x/QfVMRpOPywlmvM9cJG/jODlu2f4EKbKdylATmRRSWNBsY+uMjyPoFxp3AiHC3w/Dxt564Ts7A88wBWWMZZzosYKeUqjaYXQ/VyPnIqmo6pKPUfouZFHNSKI7ImPXp1KwmNGZkmZzp+pJ9oZWyt02LvsL2OeOZj9JkYflA/880ZFbtdT3l4cFGJB/+SpD1qeR+KFI9y3lc2kAt3LD8ZGLGiWFdILnDDCG3jpkGOPkTxoBfhsIeHf+Rq4srX8fpWC0KjBj4Z3wIx9TMHyukq6XuYuDnIrRdcSMJNeNBuI4PuSZofWjxjo5THVreB7bVWN8MrfsS7/XrPylsl/CXhlDSQBd/rmANiWhLXLZv2l4jGmhpcFSlbbxwSoJlsZBz5q7lf6GuKJM1Nhe6hlnKp3y64Pp7+P+aHqo2vqPKnPdgD1ffjRxsEzgNSJfYSWJA/sKUyNsmhzMtFIoDlomYgrqNiv+6lBi43yeGKZNFrUYssZkEh40NFMxBIfdxkxBpoEtj14xlWgAFB7/BQrU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
